"""empty message

Revision ID: 00bc1ca5fec0
Revises: d0c6a1ad139f
Create Date: 2021-01-17 11:36:22.718549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00bc1ca5fec0'
down_revision = 'd0c6a1ad139f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'player_columns')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('player_columns', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
