"""Add feedback system tables

Revision ID: 0180d991c4d8
Revises: refactor002_constraints
Create Date: 2026-01-30 07:23:19.315003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0180d991c4d8'
down_revision = 'refactor002_constraints'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('feedback_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('vote_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.ht_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.ht_id'], ),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.ht_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feedback_id', 'user_id', name='unique_user_vote')
    )
    op.alter_column('match', 'home_team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('match', 'away_team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('players', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('players', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('match', 'away_team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('match', 'home_team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('feedback_vote')
    op.drop_table('feedback_comment')
    op.drop_table('feedback')
    # ### end Alembic commands ###
