"""empty message

Revision ID: 0bcca23528ce
Revises: 5cdb5b6704e6
Create Date: 2020-06-14 17:06:07.509964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bcca23528ce'
down_revision = '5cdb5b6704e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage', sa.Column('c_update', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage', 'c_update')
    # ### end Alembic commands ###
