"""empty message

Revision ID: 187a038463ca
Revises: d0eb5b376d42
Create Date: 2020-06-14 19:21:25.389034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187a038463ca'
down_revision = 'd0eb5b376d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('is_transfer_listed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'is_transfer_listed')
    # ### end Alembic commands ###
