"""empty message

Revision ID: 2a5f899a162e
Revises: 549d2d495ba7
Create Date: 2021-01-09 12:23:28.731595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5f899a162e'
down_revision = '549d2d495ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('ht_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('home_team_name', sa.String(length=100), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_name', sa.String(length=100), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('matchtype', sa.Integer(), nullable=True),
    sa.Column('context_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('cup_level', sa.Integer(), nullable=True),
    sa.Column('cup_level_index', sa.Integer(), nullable=True),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ht_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    # ### end Alembic commands ###
