"""empty message

Revision ID: 3714bfe52d5a
Revises: 86297db66ece
Create Date: 2020-06-14 09:36:51.487476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3714bfe52d5a'
down_revision = '86297db66ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('c_login', sa.Integer(), nullable=True),
    sa.Column('c_team', sa.Integer(), nullable=True),
    sa.Column('c_player', sa.Integer(), nullable=True),
    sa.Column('c_training', sa.Integer(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_usage', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage')
    # ### end Alembic commands ###
