"""empty message

Revision ID: 3870ac6a18ac
Revises: 9400c3093630
Create Date: 2021-01-10 10:58:52.165841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3870ac6a18ac'
down_revision = '9400c3093630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('leadership', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('mother_club_bonus', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'mother_club_bonus')
    op.drop_column('players', 'leadership')
    # ### end Alembic commands ###
