"""empty message

Revision ID: 457994b4574b
Revises: 00bc1ca5fec0
Create Date: 2021-01-17 11:36:56.364957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '457994b4574b'
down_revision = '00bc1ca5fec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('player_columns', sa.PickleType(), nullable=True))
    op.drop_column('users', 'player_columns_pickled')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('player_columns_pickled', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('users', 'player_columns')
    # ### end Alembic commands ###
