"""empty message

Revision ID: 507e401c3e02
Revises: dc68ec2e347e
Create Date: 2020-06-16 17:32:07.256044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507e401c3e02'
down_revision = 'dc68ec2e347e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('access_key', sa.String(length=100), nullable=True),
    sa.Column('access_secret', sa.String(length=100), nullable=True),
    sa.Column('c_login', sa.Integer(), nullable=True),
    sa.Column('c_team', sa.Integer(), nullable=True),
    sa.Column('c_player', sa.Integer(), nullable=True),
    sa.Column('c_matches', sa.Integer(), nullable=True),
    sa.Column('c_training', sa.Integer(), nullable=True),
    sa.Column('c_update', sa.Integer(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('last_usage', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
