"""empty message

Revision ID: 549d2d495ba7
Revises: 9244890051dd
Create Date: 2020-06-25 13:29:37.591543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549d2d495ba7'
down_revision = '9244890051dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('old_owner', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'old_owner')
    # ### end Alembic commands ###
