"""empty message

Revision ID: 56061fad12c7
Revises: 3870ac6a18ac
Create Date: 2021-01-17 11:04:49.180958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56061fad12c7'
down_revision = '3870ac6a18ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('player_columns', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'player_columns')
    # ### end Alembic commands ###
