"""empty message

Revision ID: 5cdb5b6704e6
Revises: cf6566731391
Create Date: 2020-06-14 16:58:31.547056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cdb5b6704e6'
down_revision = 'cf6566731391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('ht_id', sa.Integer(), nullable=False),
    sa.Column('data_date', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('nick_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('owner_notes', sa.String(), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('age_days', sa.Integer(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('next_birthday', sa.DateTime(), nullable=True),
    sa.Column('arrival_date', sa.DateTime(), nullable=True),
    sa.Column('form', sa.Integer(), nullable=True),
    sa.Column('cards', sa.Integer(), nullable=True),
    sa.Column('injury_level', sa.Integer(), nullable=True),
    sa.Column('statement', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('agreeability', sa.Integer(), nullable=True),
    sa.Column('aggressiveness', sa.Integer(), nullable=True),
    sa.Column('honesty', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('loyalty', sa.Integer(), nullable=True),
    sa.Column('specialty', sa.Integer(), nullable=True),
    sa.Column('native_country_id', sa.Integer(), nullable=True),
    sa.Column('native_league_id', sa.Integer(), nullable=True),
    sa.Column('native_league_name', sa.String(), nullable=True),
    sa.Column('tsi', sa.Integer(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('caps', sa.Integer(), nullable=True),
    sa.Column('caps_u20', sa.Integer(), nullable=True),
    sa.Column('career_goals', sa.Integer(), nullable=True),
    sa.Column('career_hattricks', sa.Integer(), nullable=True),
    sa.Column('league_goals', sa.Integer(), nullable=True),
    sa.Column('cup_goals', sa.Integer(), nullable=True),
    sa.Column('friendly_goals', sa.Integer(), nullable=True),
    sa.Column('current_team_matches', sa.Integer(), nullable=True),
    sa.Column('current_team_goals', sa.Integer(), nullable=True),
    sa.Column('national_team_id', sa.Integer(), nullable=True),
    sa.Column('national_team_name', sa.String(), nullable=True),
    sa.Column('is_transfer_listed', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('stamina', sa.Integer(), nullable=True),
    sa.Column('keeper', sa.Integer(), nullable=True),
    sa.Column('defender', sa.Integer(), nullable=True),
    sa.Column('playmaker', sa.Integer(), nullable=True),
    sa.Column('winger', sa.Integer(), nullable=True),
    sa.Column('passing', sa.Integer(), nullable=True),
    sa.Column('scorer', sa.Integer(), nullable=True),
    sa.Column('set_pieces', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ht_id', 'data_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    # ### end Alembic commands ###
