"""empty message

Revision ID: 5d66b0acaf9a
Revises: 507e401c3e02
Create Date: 2020-06-16 22:47:55.605288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d66b0acaf9a'
down_revision = '507e401c3e02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ht_id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('ht_user', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'users', ['ht_user'])
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'ht_user')
    op.drop_column('users', 'ht_id')
    # ### end Alembic commands ###
