"""Add enhanced match analytics fields

Revision ID: 5dfd6c919450
Revises: e15df1111261
Create Date: 2026-02-05 07:38:10.943504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dfd6c919450'
down_revision = 'e15df1111261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('home_team_possession', sa.Float(), nullable=True))
    op.add_column('match', sa.Column('away_team_possession', sa.Float(), nullable=True))
    op.add_column('match', sa.Column('home_team_shots', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('away_team_shots', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('home_team_shots_on_target', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('away_team_shots_on_target', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('home_team_tackles', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('away_team_tackles', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('home_team_passes', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('away_team_passes', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('home_team_rating', sa.Float(), nullable=True))
    op.add_column('match', sa.Column('away_team_rating', sa.Float(), nullable=True))
    op.add_column('match', sa.Column('attendance', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('weather', sa.String(length=50), nullable=True))
    op.add_column('match', sa.Column('referee_name', sa.String(length=100), nullable=True))
    op.add_column('match', sa.Column('referee_country', sa.String(length=50), nullable=True))
    op.add_column('match', sa.Column('home_team_formation', sa.String(length=20), nullable=True))
    op.add_column('match', sa.Column('away_team_formation', sa.String(length=20), nullable=True))
    op.add_column('match', sa.Column('home_team_tactic', sa.String(length=50), nullable=True))
    op.add_column('match', sa.Column('away_team_tactic', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'away_team_tactic')
    op.drop_column('match', 'home_team_tactic')
    op.drop_column('match', 'away_team_formation')
    op.drop_column('match', 'home_team_formation')
    op.drop_column('match', 'referee_country')
    op.drop_column('match', 'referee_name')
    op.drop_column('match', 'weather')
    op.drop_column('match', 'attendance')
    op.drop_column('match', 'away_team_rating')
    op.drop_column('match', 'home_team_rating')
    op.drop_column('match', 'away_team_passes')
    op.drop_column('match', 'home_team_passes')
    op.drop_column('match', 'away_team_tackles')
    op.drop_column('match', 'home_team_tackles')
    op.drop_column('match', 'away_team_shots_on_target')
    op.drop_column('match', 'home_team_shots_on_target')
    op.drop_column('match', 'away_team_shots')
    op.drop_column('match', 'home_team_shots')
    op.drop_column('match', 'away_team_possession')
    op.drop_column('match', 'home_team_possession')
    # ### end Alembic commands ###
