"""Add Team model for CHPP policy compliance (REFACTOR-064)

Revision ID: 6eaa1483ce27
Revises: 8d596c5ec90f
Create Date: 2026-01-30 17:40:15.587493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eaa1483ce27'
down_revision = '8d596c5ec90f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ht_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('league_name', sa.String(length=200), nullable=True),
    sa.Column('league_level', sa.Integer(), nullable=True),
    sa.Column('power_rating', sa.Integer(), nullable=True),
    sa.Column('cup_still_in_cup', sa.Boolean(), nullable=True),
    sa.Column('cup_cup_name', sa.String(length=200), nullable=True),
    sa.Column('cup_cup_round', sa.String(length=100), nullable=True),
    sa.Column('cup_cup_round_index', sa.Integer(), nullable=True),
    sa.Column('dress_uri', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.ht_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_ht_id'), 'teams', ['ht_id'], unique=True)
    op.alter_column('feedback', 'archived',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'archived',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_teams_ht_id'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
