"""align match schema with CHPP structure - possession by halves and chance breakdown

Revision ID: 75ec6d294370
Revises: 5dfd6c919450
Create Date: 2026-02-05 13:47:12.190537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ec6d294370'
down_revision = '5dfd6c919450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('possession_first_half_home', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('possession_first_half_away', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('possession_second_half_home', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('possession_second_half_away', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('home_team_chances_left', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('home_team_chances_center', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('home_team_chances_right', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('home_team_chances_special', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('home_team_chances_other', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('away_team_chances_left', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('away_team_chances_center', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('away_team_chances_right', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('away_team_chances_special', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('away_team_chances_other', sa.Integer(), nullable=True))
    op.drop_column('match', 'home_team_passes')
    op.drop_column('match', 'away_team_passes')
    op.drop_column('match', 'away_team_tackles')
    op.drop_column('match', 'away_team_possession')
    op.drop_column('match', 'home_team_tackles')
    op.drop_column('match', 'away_team_shots')
    op.drop_column('match', 'home_team_shots')
    op.drop_column('match', 'away_team_shots_on_target')
    op.drop_column('match', 'home_team_possession')
    op.drop_column('match', 'home_team_shots_on_target')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('home_team_shots_on_target', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('match', sa.Column('home_team_possession', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('match', sa.Column('away_team_shots_on_target', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('match', sa.Column('home_team_shots', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('match', sa.Column('away_team_shots', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('match', sa.Column('home_team_tackles', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('match', sa.Column('away_team_possession', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('match', sa.Column('away_team_tackles', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('match', sa.Column('away_team_passes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('match', sa.Column('home_team_passes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('match', 'away_team_chances_other')
    op.drop_column('match', 'away_team_chances_special')
    op.drop_column('match', 'away_team_chances_right')
    op.drop_column('match', 'away_team_chances_center')
    op.drop_column('match', 'away_team_chances_left')
    op.drop_column('match', 'home_team_chances_other')
    op.drop_column('match', 'home_team_chances_special')
    op.drop_column('match', 'home_team_chances_right')
    op.drop_column('match', 'home_team_chances_center')
    op.drop_column('match', 'home_team_chances_left')
    op.drop_column('match', 'possession_second_half_away')
    op.drop_column('match', 'possession_second_half_home')
    op.drop_column('match', 'possession_first_half_away')
    op.drop_column('match', 'possession_first_half_home')
    # ### end Alembic commands ###
