"""Add matches archive tracking to User model

Revision ID: 831d57cb541f
Revises: f03b862df0b3
Create Date: 2026-02-05 16:32:54.110579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831d57cb541f'
down_revision = 'f03b862df0b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('c_matches_archive', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_matches_archive', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_matches_archive')
    op.drop_column('users', 'c_matches_archive')
    # ### end Alembic commands ###
