"""add archived field to feedback

Revision ID: 8d596c5ec90f
Revises: 0180d991c4d8
Create Date: 2026-01-30 10:48:29.296356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d596c5ec90f'
down_revision = '0180d991c4d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with default value False
    op.add_column('feedback', sa.Column('archived', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'archived')
    # ### end Alembic commands ###
