"""empty message

Revision ID: 9244890051dd
Revises: f29b1ee41e2d
Create Date: 2020-06-24 23:07:28.582815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9244890051dd'
down_revision = 'f29b1ee41e2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainingevent')
    op.drop_constraint('playersetting_player_id_key', 'playersetting', type_='unique')
    op.drop_column('playersetting', 'player_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playersetting', sa.Column('player_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('playersetting_player_id_key', 'playersetting', ['player_id'])
    op.create_table('trainingevent',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('eventdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('old_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('new_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.ht_id'], name='trainingevent_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='trainingevent_pkey')
    )
    # ### end Alembic commands ###
