"""empty message

Revision ID: 9400c3093630
Revises: ff69419a1ac0
Create Date: 2021-01-09 23:12:17.421147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9400c3093630'
down_revision = 'ff69419a1ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchplay', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('matchplay', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('matchplay', sa.Column('nick_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matchplay', 'nick_name')
    op.drop_column('matchplay', 'last_name')
    op.drop_column('matchplay', 'first_name')
    # ### end Alembic commands ###
