"""empty message

Revision ID: 97351a8d9180
Revises: 3714bfe52d5a
Create Date: 2020-06-14 11:36:29.862120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97351a8d9180'
down_revision = '3714bfe52d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage', sa.Column('c_matches', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage', 'c_matches')
    # ### end Alembic commands ###
