"""empty message

Revision ID: a81bcae87ef8
Revises: eee485027fce
Create Date: 2020-06-20 09:39:36.131643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a81bcae87ef8'
down_revision = 'eee485027fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage')
    op.create_unique_constraint(None, 'users', ['ht_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_table('usage',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('c_login', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('c_team', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('c_player', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('c_training', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_usage', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('c_matches', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('c_update', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='usage_pkey')
    )
    # ### end Alembic commands ###
