"""Add feedback formation and stats activity counters

Revision ID: adc6c266c723
Revises: c2d63625c42d
Create Date: 2026-02-01 13:23:13.263626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc6c266c723'
down_revision = 'c2d63625c42d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('c_feedback', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('c_formation', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('c_stats', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'c_stats')
    op.drop_column('users', 'c_formation')
    op.drop_column('users', 'c_feedback')
    # ### end Alembic commands ###
