"""Add settings and changes activity tracking counters

Revision ID: c2d63625c42d
Revises: 6eaa1483ce27
Create Date: 2026-02-01 13:16:46.314271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d63625c42d'
down_revision = '6eaa1483ce27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('c_settings', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('c_changes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'c_changes')
    op.drop_column('users', 'c_settings')
    # ### end Alembic commands ###
