"""Add tutorial usage counter to users

Revision ID: c50e151c8fdb
Revises: 9a80d315e2fd
Create Date: 2026-02-03 10:38:31.846707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c50e151c8fdb'
down_revision = '9a80d315e2fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('c_tutorial', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'c_tutorial')
    # ### end Alembic commands ###
