"""Replace generic tutorial counter with tour-specific tracking

Revision ID: c8f75e7975c4
Revises: c50e151c8fdb
Create Date: 2026-02-03 10:48:55.650591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f75e7975c4'
down_revision = 'c50e151c8fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('c_welcome_complete', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('c_welcome_skip', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('c_welcome_help', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('c_player_complete', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('c_player_skip', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('c_player_help', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('c_update_complete', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('c_update_skip', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('c_update_help', sa.Integer(), nullable=True))
    op.drop_column('users', 'c_tutorial')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('c_tutorial', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'c_update_help')
    op.drop_column('users', 'c_update_skip')
    op.drop_column('users', 'c_update_complete')
    op.drop_column('users', 'c_player_help')
    op.drop_column('users', 'c_player_skip')
    op.drop_column('users', 'c_player_complete')
    op.drop_column('users', 'c_welcome_help')
    op.drop_column('users', 'c_welcome_skip')
    op.drop_column('users', 'c_welcome_complete')
    # ### end Alembic commands ###
