"""empty message

Revision ID: ccf6986f8f8a
Revises: bb26b9c480a4
Create Date: 2020-06-20 21:18:55.194437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf6986f8f8a'
down_revision = 'bb26b9c480a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playergroup', sa.Column('bgcolor', sa.String(length=100), nullable=True))
    op.add_column('playergroup', sa.Column('textcolor', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'playergroup', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'playergroup', type_='unique')
    op.drop_column('playergroup', 'textcolor')
    op.drop_column('playergroup', 'bgcolor')
    # ### end Alembic commands ###
