"""empty message

Revision ID: d0c6a1ad139f
Revises: 56061fad12c7
Create Date: 2021-01-17 11:34:23.580735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c6a1ad139f'
down_revision = '56061fad12c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('player_columns_pickled', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'player_columns_pickled')
    # ### end Alembic commands ###
