"""empty message

Revision ID: d0eb5b376d42
Revises: 0bcca23528ce
Create Date: 2020-06-14 19:21:13.832183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0eb5b376d42'
down_revision = '0bcca23528ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'is_transfer_listed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('is_transfer_listed', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
