"""Add tutorial reset tracking field

Revision ID: e15df1111261
Revises: c8f75e7975c4
Create Date: 2026-02-03 10:53:06.658080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e15df1111261'
down_revision = 'c8f75e7975c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('c_tutorial_reset', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'c_tutorial_reset')
    # ### end Alembic commands ###
