"""empty message

Revision ID: ec29b80d6027
Revises: 9a30de214e3b
Create Date: 2020-06-24 17:29:01.335217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec29b80d6027'
down_revision = '9a30de214e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playersetting', sa.Column('player_type', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'playersetting', ['player_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'playersetting', type_='unique')
    op.drop_column('playersetting', 'player_type')
    # ### end Alembic commands ###
