"""empty message

Revision ID: eee485027fce
Revises: 20b1b782ed7c
Create Date: 2020-06-20 09:38:57.747339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eee485027fce'
down_revision = '20b1b782ed7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playergroup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.ht_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('playersetting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['playergroup.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.ht_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('usage')
    op.create_unique_constraint(None, 'users', ['ht_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_table('usage',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('c_login', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('c_team', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('c_player', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('c_training', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_usage', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('c_matches', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('c_update', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='usage_pkey')
    )
    op.drop_table('playersetting')
    op.drop_table('playergroup')
    # ### end Alembic commands ###
