"""add comprehensive match details - ratings positions, set pieces, arena, officials, team details

Revision ID: f03b862df0b3
Revises: 75ec6d294370
Create Date: 2026-02-05 15:13:17.281018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03b862df0b3'
down_revision = '75ec6d294370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('home_team_rating_right_def', sa.Float(), nullable=True))
    op.add_column('match', sa.Column('home_team_rating_mid_def', sa.Float(), nullable=True))
    op.add_column('match', sa.Column('home_team_rating_left_def', sa.Float(), nullable=True))
    op.add_column('match', sa.Column('away_team_rating_right_def', sa.Float(), nullable=True))
    op.add_column('match', sa.Column('away_team_rating_mid_def', sa.Float(), nullable=True))
    op.add_column('match', sa.Column('away_team_rating_left_def', sa.Float(), nullable=True))
    op.add_column('match', sa.Column('home_team_rating_right_att', sa.Float(), nullable=True))
    op.add_column('match', sa.Column('home_team_rating_mid_att', sa.Float(), nullable=True))
    op.add_column('match', sa.Column('home_team_rating_left_att', sa.Float(), nullable=True))
    op.add_column('match', sa.Column('away_team_rating_right_att', sa.Float(), nullable=True))
    op.add_column('match', sa.Column('away_team_rating_mid_att', sa.Float(), nullable=True))
    op.add_column('match', sa.Column('away_team_rating_left_att', sa.Float(), nullable=True))
    op.add_column('match', sa.Column('home_team_rating_set_pieces_def', sa.Float(), nullable=True))
    op.add_column('match', sa.Column('home_team_rating_set_pieces_att', sa.Float(), nullable=True))
    op.add_column('match', sa.Column('away_team_rating_set_pieces_def', sa.Float(), nullable=True))
    op.add_column('match', sa.Column('away_team_rating_set_pieces_att', sa.Float(), nullable=True))
    op.add_column('match', sa.Column('arena_capacity_terraces', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('arena_capacity_basic', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('arena_capacity_roof', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('arena_capacity_vip', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('weather_id', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('added_minutes', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('referee_id', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('referee_country_id', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('referee_team_id', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('referee_team_name', sa.String(length=100), nullable=True))
    op.add_column('match', sa.Column('home_team_dress_uri', sa.String(length=200), nullable=True))
    op.add_column('match', sa.Column('away_team_dress_uri', sa.String(length=200), nullable=True))
    op.add_column('match', sa.Column('home_team_attitude', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('away_team_attitude', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('home_team_tactic_type', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('home_team_tactic_skill', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('away_team_tactic_type', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('away_team_tactic_skill', sa.Integer(), nullable=True))
    op.drop_column('match', 'weather')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('weather', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('match', 'away_team_tactic_skill')
    op.drop_column('match', 'away_team_tactic_type')
    op.drop_column('match', 'home_team_tactic_skill')
    op.drop_column('match', 'home_team_tactic_type')
    op.drop_column('match', 'away_team_attitude')
    op.drop_column('match', 'home_team_attitude')
    op.drop_column('match', 'away_team_dress_uri')
    op.drop_column('match', 'home_team_dress_uri')
    op.drop_column('match', 'referee_team_name')
    op.drop_column('match', 'referee_team_id')
    op.drop_column('match', 'referee_country_id')
    op.drop_column('match', 'referee_id')
    op.drop_column('match', 'added_minutes')
    op.drop_column('match', 'weather_id')
    op.drop_column('match', 'arena_capacity_vip')
    op.drop_column('match', 'arena_capacity_roof')
    op.drop_column('match', 'arena_capacity_basic')
    op.drop_column('match', 'arena_capacity_terraces')
    op.drop_column('match', 'away_team_rating_set_pieces_att')
    op.drop_column('match', 'away_team_rating_set_pieces_def')
    op.drop_column('match', 'home_team_rating_set_pieces_att')
    op.drop_column('match', 'home_team_rating_set_pieces_def')
    op.drop_column('match', 'away_team_rating_left_att')
    op.drop_column('match', 'away_team_rating_mid_att')
    op.drop_column('match', 'away_team_rating_right_att')
    op.drop_column('match', 'home_team_rating_left_att')
    op.drop_column('match', 'home_team_rating_mid_att')
    op.drop_column('match', 'home_team_rating_right_att')
    op.drop_column('match', 'away_team_rating_left_def')
    op.drop_column('match', 'away_team_rating_mid_def')
    op.drop_column('match', 'away_team_rating_right_def')
    op.drop_column('match', 'home_team_rating_left_def')
    op.drop_column('match', 'home_team_rating_mid_def')
    op.drop_column('match', 'home_team_rating_right_def')
    # ### end Alembic commands ###
