"""empty message

Revision ID: f29b1ee41e2d
Revises: ec29b80d6027
Create Date: 2020-06-24 19:52:08.318978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29b1ee41e2d'
down_revision = 'ec29b80d6027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainingevent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('eventdate', sa.DateTime(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('old_level', sa.Integer(), nullable=True),
    sa.Column('new_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.ht_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainingevent')
    # ### end Alembic commands ###
