"""empty message

Revision ID: ff69419a1ac0
Revises: 2a5f899a162e
Create Date: 2021-01-09 22:39:11.513589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff69419a1ac0'
down_revision = '2a5f899a162e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchplay',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('rating_stars', sa.Float(), nullable=True),
    sa.Column('rating_stars_eom', sa.Float(), nullable=True),
    sa.Column('behaviour', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matchplay')
    # ### end Alembic commands ###
