"""Increase password field length for Werkzeug 3.x compatibility

Revision ID: password_field_increase_werkzeug_3x
Revises:
Create Date: 2026-01-22 10:40:00

This migration increases the password field length from VARCHAR(100) to VARCHAR(255)
to accommodate the longer password hashes generated by Werkzeug 3.x's modern
scrypt-based hashing method instead of the deprecated SHA256 method.

The new scrypt hashes are approximately 140+ characters long, requiring more space
than the previous 100-character limit.

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'password_field_increase_werkzeug_3x'
down_revision = '7e8a973e62ed'
branch_labels = None
depends_on = None


def upgrade():
    """Increase password field length to support modern Werkzeug password hashing."""
    # Increase password field from VARCHAR(100) to VARCHAR(255)
    op.alter_column('users', 'password',
                    existing_type=sa.VARCHAR(length=100),
                    type_=sa.String(length=255),
                    existing_nullable=True)


def downgrade():
    """Revert password field length to original size (WARNING: may truncate data)."""
    # Warning: This downgrade may truncate existing password data if longer than 100 chars
    op.alter_column('users', 'password',
                    existing_type=sa.VARCHAR(length=255),
                    type_=sa.String(length=100),
                    existing_nullable=True)