#!/bin/bash -ex

# Production startup script
# Changelog is generated by deployment, not at runtime

# Production environment settings
export FLASK_ENV=production

# Ensure uv is in PATH
export PATH="$HOME/.local/bin:$PATH"

# Use uv to run flask for production
env FLASK_RUN_PORT=5000 FLASK_RUN_HOST=0.0.0.0 FLASK_APP=run.py uv run flask run
