# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches-ignore: [ test/* ]
  pull_request:
    branches: [ master ]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
#      - name: Python Lint (isort/black)
#        # You may pin to the exact commit or the version.
#        # uses: wrboyce/python-lint-action@7c6d719c086f19e7eeb802c3fbdeeff6c01cab61
#        uses: wrboyce/python-lint-action@v1.0.0
      - name: Python Linter
        # You may pin to the exact commit or the version.
        # uses: sunnysid3up/python-linter@93076bd8f740f062069291d738fc70c1b4171c1d
        uses: sunnysid3up/python-linter@v0.1-beta.7
      - name: python-flake8
        # You may pin to the exact commit or the version.
        # uses: julianwachholz/flake8-action@75749239077651dfd0ecbe405899cdcb0673ee8f
        uses: julianwachholz/flake8-action@v2.0.2
