# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches-ignore: [ test/* ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Python flake8 Lint
      # You may pin to the exact commit or the version.
      # uses: py-actions/flake8@6b71483a8fe60d4cb967d3aa4ee56e5e52711d30
      uses: py-actions/flake8@v2.0.0
      with:
        # Path to source file or directory (default='.')
        path: app # optional, default is .
#        # Boolean for pip upgrade prior to flake8 installation (default='false')
#        update-pip: # optional, default is false
#        # Comma delimited list of ignored flake8 rule codes (optional)
#        ignore: # optional, default is none
#        # Comma delimited list of excluded paths (optional)
#        exclude: # optional, default is none
#        # Integer value representing max acceptable line length (optional)
#        max-line-length: # optional, default is none
#        # flake8 arguments for test execution (optional)
#        args: # optional, default is none
#        # The flake8 version for tests (optional, default='latest')
#        flake8-version: # optional, default is latest
