# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches-ignore: [ test/* ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Python Linting
      uses: WhyNotHugo/python-linting@v1.0.0
