# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches-ignore: [ test/* ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install UV
        run: pip install uv
      - name: Install dependencies
        run: make install
      - name: Run flake8 linting
        run: make lint
